{% set name = "ocifs" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ocifs-{{ version }}.tar.gz
  sha256: a4e25ee1df75ec94d74cdb3b54f1629fc32d3cd0fb6c15fc89296550a9fc45f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core >=3.8
    - pip
  run:
    - python >=3.6
    - fsspec >=0.8.7
    - oci >=2.43.1
    - requests

test:
  imports:
    - ocifs
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Convenient filesystem interface over Oracle Cloud's Object Storage
  home: https://github.com/oracle/ocifs
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
